create table visitor(
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '自增ID',
  ip VARCHAR(20) NOT NULL DEFAULT '' COMMENT 'IP地址',
  url VARCHAR(300) NOT NULL DEFAULT '' COMMENT 'url地址',
    update_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  create_at TIMESTAMP NOT NULL COMMENT '创建时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;